### ISSUE TITLE
KFPE and QFPE

### ISSUE THREAD

**Issue by lloveapple** [kaixinbear/CAPE#1]
Which part of the code is KFPE and QFPE？ Thank you.

**Comment by kaixinbear** [comment]
You can find [KFPE](https://github.com/kaixinbear/CAPE/blob/main/projects/mmdet3d_plugin/models/utils/cape_transformer.py#L422) and [QFPE](https://github.com/kaixinbear/CAPE/blob/main/projects/mmdet3d_plugin/models/utils/cape_transformer.py#L569).

**Comment by lloveapple** [comment]
谢谢

**Comment by kaixinbear** [comment]
You are welcome
