### ISSUE TITLE
Environment cannot be configured successfully

### ISSUE THREAD

**Issue by xudh777** [kaixinbear/CAPE#11]
I am very frustrated. I have tried for five days, but still haven't configured the environment properly
1、Cuda and pytorch versions
![image](https://github.com/kaixinbear/CAPE/assets/52651891/48169e7c-19cc-401f-8076-7f2e8eac2f99)
The corresponding version provided in this project is cuda11.2 and pytorch1.9.1
But I can't find the corresponding command on the PyTorch official website at all
![image](https://github.com/kaixinbear/CAPE/assets/52651891/2a587a84-991b-4d18-acc5-94d92e84beb3)
![image](https://github.com/kaixinbear/CAPE/assets/52651891/046d71fc-c8ae-4c73-8430-a95f76f534b4)
I really want to ask, what is your corresponding version？？
2、MMDetection3D
The installation commands in this project are different from those on the MMDetection3Dofficial website，I tried multiple versions of cuda and pytorch combinations, but failed to follow the guidelines of this project. I cannot determine if it is a version issue or a command issue
The environmental configuration of this project is too complex
Install.md is too simple
The cuda and pytorch versions are very suspicious
Multiple environments need to be configured, and different packages between environments are likely to have version conflicts
If there are successful individuals, we hope they can provide assistance. Thank you very much

**Comment by kaixinbear** [comment]
Sorry for unclear installation. You can build torch from wheel (https://download.pytorch.org/whl/torch_stable.html) and then try install mmdetection and mmdet3d.
I don't think specific version would be necessary for env. You can try other version. You can refer to other project for running the project, like DETR3D, PETR, StreamPETR etc.

**Comment by xudh777** [comment]
Thank you very much for your cooperation
I have tried using website  (https://download.pytorch.org/whl/torch_stable.html)  before, But unable to obtain the desired wheel file. I have some doubts about the authenticity of your environment version.  I really couldn't find the installation files and methods for cuda11.2 and pytorch 1.9.1
![微信截图_20240313095043](https://github.com/kaixinbear/CAPE/assets/52651891/e4dc3037-37bc-42b6-81af-3c24b196f31b)
![微信截图_20240313095058](https://github.com/kaixinbear/CAPE/assets/52651891/1c0848bb-d5a2-4625-9812-526640ac7b49)
I also tried some similar versions, but most of them reported errors, such as pytorch 1.11 and cuda 11.3,
![image](https://github.com/kaixinbear/CAPE/assets/52651891/f48f7a51-1238-479b-ab90-efc7b2eb035e)
There are also some conflicting versions of requirements between different packages.
Next, I will follow your suggestion and try installing it first PETR

**Comment by xudh777** [comment]
I have finally successfully configured this environment
cuda111，pytorch1.9.0
The main problem is that his environment configuration commands are too concise. When using the environment configuration command in engineering, many installation packages will install a newer version, but they use a series of projects such as mmdetection3d, which are not the latest version, resulting in conflicts between installation packages. There are many installation packages used, and the problem of conflicts between them is very serious. Moreover, your pytorch and cuda cannot use too high versions, and the mmdetection3d project does not support it
