### ISSUE TITLE
How to visualize the attention maps like in Figure 6?

### ISSUE THREAD

**Issue by sithu31296** [kaixinbear/CAPE#3]
I want to know how to visualize the attention maps of the decoder layer. Which script do you use?

**Comment by kaixinbear** [comment]
The visualization code hasn't been released yet. But you can visualize the attention maps in the following steps:
1. Run test script and save the middle variables that you want to visualize such as attention maps as .npy files.
2. Use python lib like matplotlib and opencv to plot feature maps. In this step, you can refer to [code](https://drive.google.com/file/d/1sPpOZxOLj6y7tiGZm9HMx-6ryhHMXIfg/view?usp=share_link) for visualization.

**Comment by sithu31296** [comment]
Thank you. I will try that.
