### ISSUE TITLE
Does the network use multi-level features?

### ISSUE THREAD

**Issue by LoickCh** [kaixinbear/CAPE#5]
Hello,

Thank you for your great work. I am currently looking to your code and I have a question about the use of multi-level features. Indeed, in CAPE :

- forward_train called:
    - extract_feat: outputing a list of several image features using the grid_masking, the backbone, and the neck: https://github.com/kaixinbear/CAPE/blob/main/projects/mmdet3d_plugin/models/detectors/cape.py#L73
    
    - forward_pts_train calls self.pts_bbox_head (i.e CAPEHead) forward: however, the first line of the forward is
"x = mlvl_feats[0]" (https://github.com/kaixinbear/CAPE/blob/main/projects/mmdet3d_plugin/models/dense_heads/cape_head.py#L274)

So it means only the first element of the list is used, is not it ? If I am right, only the first element is considered, meaning that CAPE does not use neither multilevel features nor the FPN.

**Comment by kaixinbear** [comment]
Yes, only the first element of the list is used. Note that this feature is the output from FPN, thus it contains the multi-level features.

**Comment by LoickCh** [comment]
Thank you, I thought the level fusion was done after FPN, but you are right, since it is done in FPN, the first element contains information from the bottom levels.
