### ISSUE TITLE
About ann_file

### ISSUE THREAD

**Issue by jjlinghu** [kaixinbear/CAPE#7]
Hi, thank you for your sharing work!
I find that the ann_file in `configs/CAPE` is different from `configs/CAPE-T`, e.g., `nuscenes_infos_train(or val).pkl` and `mmdet3d_nuscenes_30f_infos_val.pkl`. What's the difference between them? Are they all generated from `tools/create_data.py`,  just with different `--extra-tag`.
Hope your reply, thanks!

**Comment by kaixinbear** [comment]
Thanks for your attention.
"mmdet3d_nuscenes_30f_infos_val.pkl" contains sweep sensors information compared to “nuscenes_infos_train(or val)”.pkl.
“nuscenes_infos_train.pkl ” is generated by run ning"tools/create_data.py", while "mmdet3d_nuscenes_30f_infos_val.pkl" is generated by runing "tools/generate_sweep_pkl.py"

**Comment by jjlinghu** [comment]
Appreciate for your quick reply!
